import json
import os

notebook_content = {
 "nbformat": 4,
 "nbformat_minor": 2,
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Eksplorasi PCA (Eigenfaces): Melatih pada LFW vs Melatih pada Test Set\n",
    "\n",
    "`notebook_haar_cascade.ipynb` (dan turunannya) melatih PCA/Eigenfaces dengan `pca.fit()` langsung di atas ke-1000 gambar test set yang sama yang dipakai untuk evaluasi. Ini adalah **data leakage**: PCA jadi 'mengenal' distribusi piksel persis dari gambar yang dinilai, sesuatu yang tidak terjadi pada model Deep Learning (Facenet/VGG-Face/ArcFace) yang pretrained di dataset eksternal besar (VGGFace2, MS-Celeb-1M, dll) dan tidak pernah melihat test set ini saat training.\n",
    "\n",
    "Notebook ini memperbaiki hal tersebut dengan melatih basis PCA (Eigenfaces) di atas **Labeled Faces in the Wild (LFW)** — dataset wajah publik, kondisi tidak terkontrol (pose/pencahayaan/ekspresi bervariasi), yang sama sekali terpisah dari 1000 gambar test set dan ketiga foto kueri (Person A/B/C). PCA tidak butuh label identitas untuk fitting (unsupervised), jadi LFW dipakai murni sebagai kumpulan wajah generik untuk membangun eigenspace, lalu proyeksi (`transform`) dipakai pada test set seperti halnya model Deep Learning dipakai sebagai feature extractor pada wajah yang belum pernah dilihat.\n",
    "\n",
    "Notebook ini **tidak mengubah** `notebook.ipynb` / `notebook_haar_cascade.ipynb` / `notebook_mtcnn.ipynb` / `notebook_scrfd.ipynb` yang sudah ada — semuanya dibangun ulang dari nol di sini, dan kedua varian (fit-di-LFW vs fit-di-test-set) dijalankan berdampingan di notebook yang sama supaya efek leakage-nya bisa dibandingkan langsung dengan angka yang konsisten."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import cv2\n",
    "import matplotlib.pyplot as plt\n",
    "import time\n",
    "import os\n",
    "import sys\n",
    "import json\n",
    "import glob\n",
    "import random\n",
    "import psutil\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.datasets import fetch_lfw_people, get_data_home\n",
    "from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score\n",
    "from skimage.feature import local_binary_pattern\n",
    "import pandas as pd\n",
    "\n",
    "_proc = psutil.Process(os.getpid())\n",
    "\n",
    "def get_memory_usage():\n",
    "    \"\"\"RSS (Resident Set Size) proses saat ini dalam MB.\"\"\"\n",
    "    return _proc.memory_info().rss / (1024 ** 2)\n",
    "\n",
    "# Menemukan project root\n",
    "possible_roots = [\n",
    "    os.path.abspath(\".\"),\n",
    "    os.path.abspath(\"..\"),\n",
    "    os.path.abspath(\"../..\")\n",
    "]\n",
    "project_root = None\n",
    "for root in possible_roots:\n",
    "    if os.path.exists(os.path.join(root, \"core\")) and os.path.exists(os.path.join(root, \"cache_io\")):\n",
    "        project_root = root\n",
    "        break\n",
    "if project_root is None:\n",
    "    project_root = os.path.abspath(\"..\")\n",
    "\n",
    "if project_root not in sys.path:\n",
    "    sys.path.insert(0, project_root)\n",
    "print(f\"Project root diatur ke: {project_root}\")\n",
    "\n",
    "from core.detector import FaceDetector\n",
    "detector = FaceDetector()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Siapkan Training Pool dari LFW (Terpisah Total dari Test Set)\n",
    "\n",
    "`fetch_lfw_people` dari scikit-learn mengunduh (sekali saja, lalu dicache lokal) tarball `lfw-funneled` dan mengekstraknya sebagai file JPEG mentah. Kita hanya memakai fungsi ini sebagai trigger unduhan — array `.data`/`.images` yang dikembalikannya (sudah di-crop/resize oleh sklearn) tidak dipakai. Sebagai gantinya, file JPEG mentah di-glob langsung dari direktori ekstraksi lalu dijalankan lewat `FaceDetector` yang sama persis dengan yang dipakai pipeline utama, supaya alignment 5-titik & crop 112x112 konsisten dengan wajah di test set."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# min_faces_per_person besar dipakai HANYA supaya array Bunch yang dibangun sklearn kecil/cepat;\n",
    "# unduhan tarball mentah tetap penuh (seluruh 13.233 foto/5.749 identitas LFW) di disk, tidak difilter.\n",
    "print(\"Mengunduh/memuat dataset LFW (Labeled Faces in the Wild) via scikit-learn...\")\n",
    "_ = fetch_lfw_people(min_faces_per_person=20, color=True, download_if_missing=True)\n",
    "\n",
    "lfw_home = os.path.join(get_data_home(), \"lfw_home\", \"lfw_funneled\")\n",
    "lfw_image_paths = sorted(glob.glob(os.path.join(lfw_home, \"*\", \"*.jpg\")))\n",
    "print(f\"Ditemukan {len(lfw_image_paths)} foto mentah LFW di: {lfw_home}\")\n",
    "\n",
    "# Batasi jumlah foto training PCA agar waktu deteksi+alignment tetap wajar (deteksi ArcFace/MTCNN\n",
    "# di 1000 foto test set butuh ~4 menit, lihat notebook_haar_cascade.ipynb). None = pakai semua.\n",
    "LFW_TRAIN_LIMIT = 2000\n",
    "random.seed(42)\n",
    "random.shuffle(lfw_image_paths)\n",
    "if LFW_TRAIN_LIMIT is not None:\n",
    "    lfw_image_paths = lfw_image_paths[:LFW_TRAIN_LIMIT]\n",
    "print(f\"Dipakai untuk training PCA: {len(lfw_image_paths)} foto (diacak, seed=42).\")\n",
    "\n",
    "print(\"Menjalankan deteksi & alignment wajah pada training pool LFW...\")\n",
    "t0 = time.time()\n",
    "lfw_faces = []\n",
    "for img_path in lfw_image_paths:\n",
    "    try:\n",
    "        rois = detector.detect_and_crop(img_path)\n",
    "    except Exception:\n",
    "        continue\n",
    "    if rois:\n",
    "        lfw_faces.append(rois[0][\"cropped_face\"])\n",
    "lfw_detect_time = time.time() - t0\n",
    "print(f\"Berhasil mengumpulkan {len(lfw_faces)} wajah LFW ter-align dalam {lfw_detect_time:.2f} detik.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Fit PCA (Eigenfaces) & LBP+PCA Hibrida di atas Training Pool LFW\n",
    "\n",
    "Basis PCA dilatih (`pca.fit`) hanya sekali di sini, di atas wajah-wajah LFW. Model yang sudah di-fit ini (`pca_global`, `pca_lbp_global`) selanjutnya HANYA dipakai untuk `.transform()` pada test set & kueri — persis pola pretrained model Deep Learning sebagai feature extractor tetap."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def flatten_gray_face(face_img):\n",
    "    gray = cv2.cvtColor(face_img, cv2.COLOR_BGR2GRAY)\n",
    "    return gray.flatten().astype(np.float32) / 255.0\n",
    "\n",
    "def extract_raw_lbp(face_img, radius=1, n_points=8):\n",
    "    gray = cv2.cvtColor(face_img, cv2.COLOR_BGR2GRAY)\n",
    "    lbp = local_binary_pattern(gray, n_points, radius, method=\"uniform\")\n",
    "    return lbp.ravel().astype(np.float32)\n",
    "\n",
    "def extract_lbp_hist(face_img, radius=1, n_points=8):\n",
    "    gray = cv2.cvtColor(face_img, cv2.COLOR_BGR2GRAY)\n",
    "    lbp = local_binary_pattern(gray, n_points, radius, method=\"uniform\")\n",
    "    n_bins = n_points + 2\n",
    "    hist, _ = np.histogram(lbp.ravel(), bins=n_bins, range=(0, n_bins), density=True)\n",
    "    return hist.astype(np.float32)\n",
    "\n",
    "print(\"Fitting PCA (Eigenfaces) di atas training pool LFW...\")\n",
    "t0 = time.time()\n",
    "lfw_flat = np.array([flatten_gray_face(f) for f in lfw_faces])\n",
    "n_components = min(150, len(lfw_faces))\n",
    "pca_global = PCA(n_components=n_components, svd_solver='randomized', whiten=True)\n",
    "pca_global.fit(lfw_flat)\n",
    "pca_global_fit_time = time.time() - t0\n",
    "print(f\"PCA (Eigenfaces) selesai fit ({n_components} komponen) dalam {pca_global_fit_time:.2f} detik. \"\n",
    "      f\"Explained variance: {pca_global.explained_variance_ratio_.sum():.4f}\")\n",
    "\n",
    "print(\"\\nFitting LBP + PCA Hibrida di atas training pool LFW...\")\n",
    "t0 = time.time()\n",
    "lfw_raw_lbp = np.array([extract_raw_lbp(f) for f in lfw_faces])\n",
    "n_components_hyb = min(50, len(lfw_faces))\n",
    "pca_lbp_global = PCA(n_components=n_components_hyb, svd_solver='randomized', whiten=True)\n",
    "pca_lbp_global.fit(lfw_raw_lbp)\n",
    "pca_lbp_global_fit_time = time.time() - t0\n",
    "print(f\"LBP + PCA Hibrida selesai fit ({n_components_hyb} komponen) dalam {pca_lbp_global_fit_time:.2f} detik. \"\n",
    "      f\"Explained variance: {pca_lbp_global.explained_variance_ratio_.sum():.4f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Muat Test Set (1000 Foto) & Kueri (Person A/B/C)\n",
    "Sama seperti `notebook_haar_cascade.ipynb`: dataset uji dari `D:\\dataset\\testset`, ground truth dari `ground_truth.json`. Bagian ini tidak menyentuh PCA sama sekali — murni pengumpulan wajah untuk dievaluasi."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "TESTSET_DIR = \"D:/dataset/testset\"\n",
    "TEST_IMAGES_DIR = os.path.join(TESTSET_DIR, \"test_case\")\n",
    "QUERIES_DIR = os.path.join(TESTSET_DIR, \"queries\")\n",
    "GROUND_TRUTH_PATH = os.path.join(TESTSET_DIR, \"ground_truth.json\")\n",
    "\n",
    "with open(GROUND_TRUTH_PATH, \"r\", encoding=\"utf-8\") as f:\n",
    "    ground_truth = json.load(f)\n",
    "\n",
    "test_images = [f for f in os.listdir(TEST_IMAGES_DIR) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]\n",
    "LIMIT_IMAGES = 1000  # Ganti dengan angka kecil untuk pengujian cepat, atau None untuk seluruh gambar\n",
    "if LIMIT_IMAGES is not None:\n",
    "    test_images = test_images[:LIMIT_IMAGES]\n",
    "print(f\"Total Gambar Uji: {len(test_images)}\")\n",
    "\n",
    "queries = {\n",
    "    \"A\": os.path.join(QUERIES_DIR, \"selfie_A.jpeg\"),\n",
    "    \"B\": os.path.join(QUERIES_DIR, \"selfie_B.jpg\"),\n",
    "    \"C\": os.path.join(QUERIES_DIR, \"selfie_C.jpg\")\n",
    "}\n",
    "query_faces = {}\n",
    "for person, path in queries.items():\n",
    "    faces = detector.detect_and_crop(path)\n",
    "    if faces:\n",
    "        query_faces[person] = faces[0][\"cropped_face\"]\n",
    "        print(f\"Wajah kueri Person {person} berhasil dideteksi.\")\n",
    "    else:\n",
    "        raise RuntimeError(f\"Gagal mendeteksi wajah pada kueri: {path}\")\n",
    "\n",
    "print(\"Mengumpulkan wajah dari dataset gambar uji...\")\n",
    "t0 = time.time()\n",
    "dataset_faces = []  # list of dict: {\"img_name\": str, \"cropped_face\": np.ndarray, \"bbox\": tuple}\n",
    "for img_name in test_images:\n",
    "    img_path = os.path.join(TEST_IMAGES_DIR, img_name)\n",
    "    rois = detector.detect_and_crop(img_path)\n",
    "    for roi in rois:\n",
    "        dataset_faces.append({\n",
    "            \"img_name\": img_name,\n",
    "            \"cropped_face\": roi[\"cropped_face\"],\n",
    "            \"bbox\": roi[\"bbox\"]\n",
    "        })\n",
    "print(f\"Berhasil mengumpulkan {len(dataset_faces)} wajah dari {len(test_images)} gambar uji \"\n",
    "      f\"dalam {time.time() - t0:.2f} detik.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Fungsi Evaluasi (Cosine Distance, Grid-Search Threshold)\n",
    "Identik dengan `evaluate_matching_model` di `notebook_haar_cascade.ipynb`, supaya angka F1/Accuracy yang dihasilkan bisa dibandingkan apel-ke-apel."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "results = {\n",
    "    'Model': [],\n",
    "    'Accuracy': [],\n",
    "    'Precision': [],\n",
    "    'Recall': [],\n",
    "    'F1-Score': [],\n",
    "    'Best Threshold': [],\n",
    "    'Fit Time (s)': [],\n",
    "    'Transform + Inference Time (s)': [],\n",
    "}\n",
    "\n",
    "def evaluate_matching_model(model_name, query_feats, dataset_feats, dataset_face_metadata, fit_time, infer_extra_time=0.0):\n",
    "    t0 = time.time()\n",
    "    persons = [\"A\", \"B\", \"C\"]\n",
    "    distances = {}\n",
    "    for p in persons:\n",
    "        q_feat = query_feats[p]\n",
    "        q_norm = q_feat / (np.linalg.norm(q_feat) + 1e-10)\n",
    "        ds_norms = np.linalg.norm(dataset_feats, axis=1, keepdims=True) + 1e-10\n",
    "        ds_normed = dataset_feats / ds_norms\n",
    "        sims = np.dot(ds_normed, q_norm)\n",
    "        sims = np.clip(sims, -1.0, 1.0)\n",
    "        distances[p] = 1.0 - sims\n",
    "\n",
    "    thresholds = np.arange(0.05, 1.0, 0.05)\n",
    "    best_f1 = -1\n",
    "    best_thresh = 0.4\n",
    "    best_metrics = {}\n",
    "\n",
    "    y_true = []\n",
    "    for img_name in test_images:\n",
    "        gt_img = ground_truth.get(img_name, {\"contains_person_A\": False, \"contains_person_B\": False, \"contains_person_C\": False})\n",
    "        y_true.append(gt_img.get(\"contains_person_A\", False))\n",
    "        y_true.append(gt_img.get(\"contains_person_B\", False))\n",
    "        y_true.append(gt_img.get(\"contains_person_C\", False))\n",
    "    y_true = np.array(y_true, dtype=bool)\n",
    "\n",
    "    for thresh in thresholds:\n",
    "        y_pred = []\n",
    "        for img_name in test_images:\n",
    "            indices = [i for i, meta in enumerate(dataset_face_metadata) if meta[\"img_name\"] == img_name]\n",
    "            for p in persons:\n",
    "                if not indices:\n",
    "                    y_pred.append(False)\n",
    "                else:\n",
    "                    min_dist = np.min(distances[p][indices])\n",
    "                    y_pred.append(min_dist <= thresh)\n",
    "        y_pred = np.array(y_pred, dtype=bool)\n",
    "        f1 = f1_score(y_true, y_pred, zero_division=0)\n",
    "        if f1 > best_f1:\n",
    "            best_f1 = f1\n",
    "            best_thresh = thresh\n",
    "            best_metrics = {\n",
    "                'Accuracy': accuracy_score(y_true, y_pred),\n",
    "                'Precision': precision_score(y_true, y_pred, zero_division=0),\n",
    "                'Recall': recall_score(y_true, y_pred, zero_division=0),\n",
    "                'F1-Score': f1\n",
    "            }\n",
    "\n",
    "    infer_time = (time.time() - t0) + infer_extra_time\n",
    "\n",
    "    results['Model'].append(model_name)\n",
    "    results['Accuracy'].append(best_metrics['Accuracy'])\n",
    "    results['Precision'].append(best_metrics['Precision'])\n",
    "    results['Recall'].append(best_metrics['Recall'])\n",
    "    results['F1-Score'].append(best_metrics['F1-Score'])\n",
    "    results['Best Threshold'].append(best_thresh)\n",
    "    results['Fit Time (s)'].append(fit_time)\n",
    "    results['Transform + Inference Time (s)'].append(infer_time)\n",
    "\n",
    "    print(f\"--- {model_name} Evaluated ---\")\n",
    "    print(f\"Best Threshold: {best_thresh:.2f}\")\n",
    "    print(f\"Accuracy      : {best_metrics['Accuracy']:.4f}\")\n",
    "    print(f\"Precision     : {best_metrics['Precision']:.4f}\")\n",
    "    print(f\"Recall        : {best_metrics['Recall']:.4f}\")\n",
    "    print(f\"F1-Score      : {best_metrics['F1-Score']:.4f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Evaluasi: PCA (Eigenfaces) Dilatih di LFW — Tanpa Leakage\n",
    "`pca_global` tidak pernah melihat test set ataupun kueri A/B/C. Hanya `.transform()` yang dipanggil di sini."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Evaluasi PCA (Eigenfaces, fit di LFW)...\")\n",
    "t0 = time.time()\n",
    "query_flat = np.array([flatten_gray_face(query_faces[p]) for p in [\"A\", \"B\", \"C\"]])\n",
    "dataset_flat = np.array([flatten_gray_face(f[\"cropped_face\"]) for f in dataset_faces])\n",
    "\n",
    "query_projected = pca_global.transform(query_flat)\n",
    "dataset_projected = pca_global.transform(dataset_flat)\n",
    "query_feats = {p: query_projected[i] for i, p in enumerate([\"A\", \"B\", \"C\"])}\n",
    "transform_time = time.time() - t0\n",
    "\n",
    "evaluate_matching_model('PCA (Fit di LFW)', query_feats, dataset_projected, dataset_faces,\n",
    "                         fit_time=pca_global_fit_time, infer_extra_time=transform_time)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Evaluasi: LBP + PCA Hibrida Dilatih di LFW — Tanpa Leakage"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Evaluasi LBP + PCA Hibrida (fit di LFW)...\")\n",
    "t0 = time.time()\n",
    "query_raw_lbp = np.array([extract_raw_lbp(query_faces[p]) for p in [\"A\", \"B\", \"C\"]])\n",
    "dataset_raw_lbp = np.array([extract_raw_lbp(f[\"cropped_face\"]) for f in dataset_faces])\n",
    "\n",
    "query_projected = pca_lbp_global.transform(query_raw_lbp)\n",
    "dataset_projected = pca_lbp_global.transform(dataset_raw_lbp)\n",
    "query_feats = {p: query_projected[i] for i, p in enumerate([\"A\", \"B\", \"C\"])}\n",
    "transform_time = time.time() - t0\n",
    "\n",
    "evaluate_matching_model('LBP + PCA Hibrida (Fit di LFW)', query_feats, dataset_projected, dataset_faces,\n",
    "                         fit_time=pca_lbp_global_fit_time, infer_extra_time=transform_time)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Baseline Pembanding: PCA & Hibrida Di-fit Langsung di Test Set (Leakage)\n",
    "Direplikasi persis dari `notebook_haar_cascade.ipynb` supaya efek menghapus leakage bisa dibandingkan berdampingan di run yang sama, bukan mengandalkan angka hasil run lama."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Evaluasi PCA (Eigenfaces, fit di test set — Leakage)...\")\n",
    "t0 = time.time()\n",
    "pca_leak = PCA(n_components=min(150, len(dataset_faces)), svd_solver='randomized', whiten=True)\n",
    "pca_leak.fit(dataset_flat)\n",
    "fit_time_leak = time.time() - t0\n",
    "\n",
    "t0 = time.time()\n",
    "query_projected = pca_leak.transform(query_flat)\n",
    "dataset_projected = pca_leak.transform(dataset_flat)\n",
    "query_feats = {p: query_projected[i] for i, p in enumerate([\"A\", \"B\", \"C\"])}\n",
    "transform_time = time.time() - t0\n",
    "\n",
    "evaluate_matching_model('PCA (Fit di Test Set - Leakage)', query_feats, dataset_projected, dataset_faces,\n",
    "                         fit_time=fit_time_leak, infer_extra_time=transform_time)\n",
    "\n",
    "print(\"\\nEvaluasi LBP + PCA Hibrida (fit di test set — Leakage)...\")\n",
    "t0 = time.time()\n",
    "pca_lbp_leak = PCA(n_components=min(50, len(dataset_faces)), svd_solver='randomized', whiten=True)\n",
    "pca_lbp_leak.fit(dataset_raw_lbp)\n",
    "fit_time_leak = time.time() - t0\n",
    "\n",
    "t0 = time.time()\n",
    "query_projected = pca_lbp_leak.transform(query_raw_lbp)\n",
    "dataset_projected = pca_lbp_leak.transform(dataset_raw_lbp)\n",
    "query_feats = {p: query_projected[i] for i, p in enumerate([\"A\", \"B\", \"C\"])}\n",
    "transform_time = time.time() - t0\n",
    "\n",
    "evaluate_matching_model('LBP + PCA Hibrida (Fit di Test Set - Leakage)', query_feats, dataset_projected, dataset_faces,\n",
    "                         fit_time=fit_time_leak, infer_extra_time=transform_time)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Perbandingan: LFW (Tanpa Leakage) vs Test Set (Leakage)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_results = pd.DataFrame(results)\n",
    "print(\"\\n--- Hasil Perbandingan PCA: LFW vs Test Set (Leakage) ---\")\n",
    "print(df_results.to_string(index=False))\n",
    "\n",
    "colors = ['#4E79A7', '#F28E2B', '#E15759', '#76B7B2']\n",
    "plt.figure(figsize=(10, 6))\n",
    "bars = plt.bar(df_results['Model'], df_results['F1-Score'], color=colors[:len(df_results)])\n",
    "plt.title('F1-Score: PCA Fit di LFW (Tanpa Leakage) vs Fit di Test Set (Leakage)', fontsize=12, fontweight='bold')\n",
    "plt.ylim(0, 1.0)\n",
    "plt.xticks(rotation=20, ha='right', fontsize=9)\n",
    "plt.ylabel('F1-Score')\n",
    "for bar in bars:\n",
    "    yval = bar.get_height()\n",
    "    plt.text(bar.get_x() + bar.get_width() / 2.0, yval + 0.02, f\"{yval:.3f}\", ha='center', va='bottom', fontsize=9)\n",
    "\n",
    "plt.tight_layout()\n",
    "assets_dir = os.path.join(project_root, \"assets\")\n",
    "os.makedirs(assets_dir, exist_ok=True)\n",
    "plt.savefig(os.path.join(assets_dir, \"perbandingan_pca_lfw_vs_leakage.png\"), dpi=300, bbox_inches=\"tight\")\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.0"
  }
 }
}

current_dir = os.path.dirname(os.path.abspath(__file__))
notebook_path = os.path.join(current_dir, "notebook_pca_lfw.ipynb")
with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(notebook_content, f, indent=1)
print(f"Jupyter Notebook (PCA vs LFW) berhasil dibentuk di: {notebook_path}")
