import json
import os

notebook_content = {
 "nbformat": 4,
 "nbformat_minor": 2,
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Eksplorasi Algoritma Face Recognition\n",
    "\n",
    "Notebook ini bertujuan untuk membandingkan delapan metode pengenalan wajah sesuai dengan uji yang dilakukan di sistem GUI:\n",
    "1. **Geometry-Based (Geometric Landmarks)**\n",
    "2. **PCA (Holistik)**\n",
    "3. **LBP (Berbasis Fitur)**\n",
    "4. **HOG (Berbasis Fitur)**\n",
    "5. **LBP + PCA (Hibrida)**\n",
    "6. **DeepFace - Facenet (Deep Learning)**\n",
    "7. **DeepFace - VGG-Face (Deep Learning)**\n",
    "8. **DeepFace - ArcFace (Deep Learning)**\n",
    "\n",
    "Pengujian dilakukan dengan mencocokkan foto selfie kueri (Person A, B, C) dengan seluruh 1000 gambar uji di dataset, menggunakan metode pencocokan jarak Cosine langsung (tanpa SVM) seperti pada sistem GUI. Evaluasi akan mencari threshold optimal untuk masing-masing model untuk perbandingan yang adil."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import cv2\n",
    "import matplotlib.pyplot as plt\n",
    "import time\n",
    "import os\n",
    "import psutil\n",
    "import sys\n",
    "import json\n",
    "import hashlib\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score\n",
    "from skimage.feature import local_binary_pattern, hog\n",
    "from deepface import DeepFace\n",
    "import pandas as pd\n",
    "\n",
    "# Fungsi untuk mendapatkan penggunaan memori saat ini dalam MB\n",
    "def get_memory_usage():\n",
    "    process = psutil.Process(os.getpid())\n",
    "    return process.memory_info().rss / (1024 ** 2)\n",
    "\n",
    "# Menemukan project root\n",
    "possible_roots = [\n",
    "    os.path.abspath(\".\"),\n",
    "    os.path.abspath(\"..\"),\n",
    "    os.path.abspath(\"../..\")\n",
    "]\n",
    "project_root = None\n",
    "for root in possible_roots:\n",
    "    if os.path.exists(os.path.join(root, \"core\")) and os.path.exists(os.path.join(root, \"cache_io\")):\n",
    "        project_root = root\n",
    "        break\n",
    "if project_root is None:\n",
    "    project_root = os.path.abspath(\"..\")\n",
    "\n",
    "if project_root not in sys.path:\n",
    "    sys.path.insert(0, project_root)\n",
    "print(f\"Project root diatur ke: {project_root}\")\n",
    "\n",
    "from core.detector import FaceDetector\n",
    "from cache_io.cache_handler import CacheHandler"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Persiapan Dataset & Integrasi Cache\n",
    "Memuat dataset pengujian dari `D:\\dataset\\testset`, foto kueri dari `queries/`, ground truth dari `ground_truth.json`, dan inisialisasi model cache terpisah untuk masing-masing model Deep Learning menggunakan `CacheHandler` dari `cache_io`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "TESTSET_DIR = \"D:/dataset/testset\"\n",
    "TEST_IMAGES_DIR = os.path.join(TESTSET_DIR, \"test_case\")\n",
    "QUERIES_DIR = os.path.join(TESTSET_DIR, \"queries\")\n",
    "GROUND_TRUTH_PATH = os.path.join(TESTSET_DIR, \"ground_truth.json\")\n",
    "\n",
    "# 1. Load Ground Truth\n",
    "with open(GROUND_TRUTH_PATH, \"r\", encoding=\"utf-8\") as f:\n",
    "    ground_truth = json.load(f)\n",
    "\n",
    "test_images = [f for f in os.listdir(TEST_IMAGES_DIR) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]\n",
    "LIMIT_IMAGES = 15  # Ganti dengan angka (misal 100) untuk pengujian cepat, atau None untuk seluruh gambar\n",
    "if LIMIT_IMAGES is not None:\n",
    "    test_images = test_images[:LIMIT_IMAGES]\n",
    "print(f\"Total Gambar Uji: {len(test_images)}\")\n",
    "print(f\"Total Gambar di Ground Truth: {len(ground_truth)}\")\n",
    "\n",
    "# 2. Inisialisasi Face Detector\n",
    "detector = FaceDetector()\n",
    "\n",
    "# 3. Subclass CacheHandler untuk menentukan direktori cache secara dinamis per model\n",
    "class ModelCacheHandler(CacheHandler):\n",
    "    def __init__(self, folder_input_path: str, model_name: str):\n",
    "        super().__init__(folder_input_path)\n",
    "        self.model_name = model_name.lower()\n",
    "        self.cache_dir = os.path.join(self.folder_input_path, f\".face_cache_{self.model_name}\")\n",
    "        os.makedirs(self.cache_dir, exist_ok=True)\n",
    "\n",
    "    def cache_exists(self, file_name: str, bbox: tuple) -> bool:\n",
    "        bbox_str = f\"_{bbox[0]}_{bbox[1]}_{bbox[2]}_{bbox[3]}\"\n",
    "        unique_id = hashlib.md5((file_name + bbox_str).encode('utf-8')).hexdigest()\n",
    "        cache_file_path = os.path.join(self.cache_dir, f\"{unique_id}.json\")\n",
    "        return os.path.exists(cache_file_path)\n",
    "\n",
    "# 4. Load Preloaded Cache untuk efisiensi eksekusi notebook\n",
    "models_dl = [\"ArcFace\", \"Facenet\", \"VGG-Face\"]\n",
    "handlers = {model: ModelCacheHandler(TEST_IMAGES_DIR, model) for model in models_dl}\n",
    "preloaded_caches = {}\n",
    "\n",
    "for model in models_dl:\n",
    "    print(f\"Memuat cache untuk model {model}...\")\n",
    "    cache_list = handlers[model].muat_seluruh_cache()\n",
    "    model_cache = {}\n",
    "    for entry in cache_list:\n",
    "        img_name = entry[\"file_name\"]\n",
    "        if img_name not in model_cache:\n",
    "            model_cache[img_name] = []\n",
    "        model_cache[img_name].append(entry)\n",
    "    preloaded_caches[model] = model_cache\n",
    "\n",
    "# 5. Helper untuk memuat wajah (face ROIs) — selalu menggunakan detector untuk alignment konsisten\n",
    "def get_face_rois(img_path, detector):\n",
    "    # Selalu jalankan detector.detect_and_crop agar affine alignment 5-titik diterapkan\n",
    "    # secara konsisten di setiap run, tanpa bergantung pada cache bbox yang mungkin\n",
    "    # dihasilkan oleh detector berbeda atau tanpa alignment.\n",
    "    return detector.detect_and_crop(img_path)\n",
    "\n",
    "def extract_deepface_embedding(face_img, model_name):\n",
    "    if len(face_img.shape) == 2:\n",
    "        face_img = cv2.cvtColor(face_img, cv2.COLOR_GRAY2BGR)\n",
    "    elif face_img.shape[2] == 4:\n",
    "        face_img = face_img[:, :, :3]\n",
    "    # Downscale check for safe preprocessing\n",
    "    h_f, w_f = face_img.shape[:2]\n",
    "    if max(h_f, w_f) > 1080:\n",
    "        scale_f = 1080.0 / max(h_f, w_f)\n",
    "        face_img = cv2.resize(face_img, (int(w_f * scale_f), int(h_f * scale_f)), interpolation=cv2.INTER_AREA)\n",
    "    objs = DeepFace.represent(\n",
    "        img_path=face_img,\n",
    "        model_name=model_name,\n",
    "        enforce_detection=False,\n",
    "        detector_backend=\"skip\"\n",
    "    )\n",
    "    return np.array(objs[0]['embedding'], dtype=np.float32)\n",
    "\n",
    "# 6. Ekstraksi Wajah untuk Kueri\n",
    "queries = {\n",
    "    \"A\": os.path.join(QUERIES_DIR, \"selfie_A.jpeg\"),\n",
    "    \"B\": os.path.join(QUERIES_DIR, \"selfie_B.jpg\"),\n",
    "    \"C\": os.path.join(QUERIES_DIR, \"selfie_C.jpg\")\n",
    "}\n",
    "query_faces = {}\n",
    "for person, path in queries.items():\n",
    "    faces = detector.detect_and_crop(path)\n",
    "    if faces:\n",
    "        query_faces[person] = faces[0][\"cropped_face\"]\n",
    "        print(f\"Wajah kueri Person {person} berhasil dideteksi.\")\n",
    "    else:\n",
    "        raise RuntimeError(f\"Gagal mendeteksi wajah pada kueri: {path}\")\n",
    "\n",
    "# 7. Kumpulkan semua wajah terdeteksi dari dataset gambar uji (Face Cropping tunggal untuk keadilan evaluasi)\n",
    "print(\"Mengumpulkan wajah dari dataset gambar uji...\")\n",
    "t0 = time.time()\n",
    "dataset_faces = [] # list of dict: {\"img_name\": str, \"cropped_face\": np.ndarray, \"bbox\": tuple}\n",
    "for img_name in test_images:\n",
    "    img_path = os.path.join(TEST_IMAGES_DIR, img_name)\n",
    "    rois = get_face_rois(img_path, detector)\n",
    "    for roi in rois:\n",
    "        dataset_faces.append({\n",
    "            \"img_name\": img_name,\n",
    "            \"cropped_face\": roi[\"cropped_face\"],\n",
    "            \"bbox\": roi[\"bbox\"]\n",
    "        })\n",
    "detection_time = time.time() - t0\n",
    "print(f\"Berhasil mengumpulkan {len(dataset_faces)} wajah dari {len(test_images)} gambar uji dalam {detection_time:.2f} detik (deteksi+alignment).\")\n",
    "\n",
    "# Penampung hasil komparasi\n",
    "results = {\n",
    "    'Model': [],\n",
    "    'Accuracy': [],\n",
    "    'Precision': [],\n",
    "    'Recall': [],\n",
    "    'F1-Score': [],\n",
    "    'Best Threshold': [],\n",
    "    'Feature Extraction Time (s)': [],\n",
    "    'Inference Time (s)': [],\n",
    "    'Memory Usage (MB)': [],\n",
    "    'Detection Time (s)': []\n",
    "}\n",
    "\n",
    "# Fungsi pembantu evaluasi umum\n",
    "def evaluate_matching_model(model_name, query_feats, dataset_feats, dataset_face_metadata, feat_extract_time, mem_used):\n",
    "    t0 = time.time()\n",
    "    # Evaluasi jarak Cosine secara matriks/ter-vektorisasi\n",
    "    # query_feats: dict of {person: vector}\n",
    "    # dataset_feats: array of shape (N_faces, dim)\n",
    "    \n",
    "    persons = [\"A\", \"B\", \"C\"]\n",
    "    # Hitung semua jarak Cosine antara kueri dan wajah di dataset\n",
    "    # Jarak Cosine = 1.0 - Cosine Similarity\n",
    "    distances = {}\n",
    "    for p in persons:\n",
    "        q_feat = query_feats[p]\n",
    "        q_norm = q_feat / (np.linalg.norm(q_feat) + 1e-10)\n",
    "        \n",
    "        # dataset_feats shape (N, dim)\n",
    "        ds_norms = np.linalg.norm(dataset_feats, axis=1, keepdims=True) + 1e-10\n",
    "        ds_normed = dataset_feats / ds_norms\n",
    "        \n",
    "        sims = np.dot(ds_normed, q_norm)\n",
    "        sims = np.clip(sims, -1.0, 1.0)\n",
    "        distances[p] = 1.0 - sims\n",
    "        \n",
    "    # Mencari threshold optimal dari 0.05 ke 0.95 dengan step 0.05\n",
    "    thresholds = np.arange(0.05, 1.0, 0.05)\n",
    "    best_f1 = -1\n",
    "    best_thresh = 0.4\n",
    "    best_metrics = {}\n",
    "    \n",
    "    # Struktur data target (ground truth)\n",
    "    # Bentuk ground truth flat (1000 gambar * 3 orang = 3000 pasang)\n",
    "    y_true = []\n",
    "    for img_name in test_images:\n",
    "        gt_img = ground_truth.get(img_name, {\"contains_person_A\": False, \"contains_person_B\": False, \"contains_person_C\": False})\n",
    "        y_true.append(gt_img.get(\"contains_person_A\", False))\n",
    "        y_true.append(gt_img.get(\"contains_person_B\", False))\n",
    "        y_true.append(gt_img.get(\"contains_person_C\", False))\n",
    "    y_true = np.array(y_true, dtype=bool)\n",
    "    \n",
    "    # Lakukan grid search threshold\n",
    "    for thresh in thresholds:\n",
    "        # Lakukan prediksi untuk setiap gambar uji\n",
    "        y_pred = []\n",
    "        for img_name in test_images:\n",
    "            # Cari indeks wajah-wajah yang terdeteksi di gambar ini\n",
    "            indices = [i for i, meta in enumerate(dataset_face_metadata) if meta[\"img_name\"] == img_name]\n",
    "            \n",
    "            for p in persons:\n",
    "                if not indices:\n",
    "                    # Tidak ada wajah terdeteksi\n",
    "                    y_pred.append(False)\n",
    "                else:\n",
    "                    # Ambil jarak terkecil (wajah paling mirip) untuk kueri person p\n",
    "                    min_dist = np.min(distances[p][indices])\n",
    "                    y_pred.append(min_dist <= thresh)\n",
    "                    \n",
    "        y_pred = np.array(y_pred, dtype=bool)\n",
    "        f1 = f1_score(y_true, y_pred, zero_division=0)\n",
    "        if f1 > best_f1:\n",
    "            best_f1 = f1\n",
    "            best_thresh = thresh\n",
    "            best_metrics = {\n",
    "                'Accuracy': accuracy_score(y_true, y_pred),\n",
    "                'Precision': precision_score(y_true, y_pred, zero_division=0),\n",
    "                'Recall': recall_score(y_true, y_pred, zero_division=0),\n",
    "                'F1-Score': f1\n",
    "            }\n",
    "            \n",
    "    infer_time = time.time() - t0\n",
    "    \n",
    "    # Catat ke tabel komparasi\n",
    "    results['Model'].append(model_name)\n",
    "    results['Accuracy'].append(best_metrics['Accuracy'])\n",
    "    results['Precision'].append(best_metrics['Precision'])\n",
    "    results['Recall'].append(best_metrics['Recall'])\n",
    "    results['F1-Score'].append(best_metrics['F1-Score'])\n",
    "    results['Best Threshold'].append(best_thresh)\n",
    "    results['Feature Extraction Time (s)'].append(feat_extract_time)\n",
    "    results['Inference Time (s)'].append(infer_time)\n",
    "    results['Memory Usage (MB)'].append(mem_used)\n",
    "    results['Detection Time (s)'].append(detection_time)\n",
    "    \n",
    "    print(f\"--- {model_name} Evaluated ---\")\n",
    "    print(f\"Best Threshold: {best_thresh:.2f}\")\n",
    "    print(f\"Accuracy      : {best_metrics['Accuracy']:.4f}\")\n",
    "    print(f\"F1-Score      : {best_metrics['F1-Score']:.4f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Metode Berbasis Geometri: Geometry-Based Landmarks\n",
    "Metode berbasis geometri mengidentifikasi wajah dengan mengukur jarak relatif antar landmark wajah utama seperti mata, hidung, dan mulut secara scale-invariant pada 6 jarak Euclidean berpasangan."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def extract_geometry_features(face_img):\n",
    "    gray = cv2.cvtColor(face_img, cv2.COLOR_BGR2GRAY)\n",
    "    h_idx, w_idx = gray.shape\n",
    "    \n",
    "    def get_landmark_centroid(y_start, y_end, x_start, x_end):\n",
    "        ys, ye = int(y_start * h_idx), int(y_end * h_idx)\n",
    "        xs, xe = int(x_start * w_idx), int(x_end * w_idx)\n",
    "        sub_img = gray[ys:ye, xs:xe]\n",
    "        \n",
    "        threshold = np.percentile(sub_img, 10)\n",
    "        dark_pixels = np.argwhere(sub_img <= threshold)\n",
    "        if len(dark_pixels) == 0:\n",
    "            cy, cx = (ys + ye) / 2, (xs + xe) / 2\n",
    "        else:\n",
    "            cy = ys + np.mean(dark_pixels[:, 0])\n",
    "            cx = xs + np.mean(dark_pixels[:, 1])\n",
    "        return np.array([cx, cy])\n",
    "        \n",
    "    left_eye = get_landmark_centroid(0.2, 0.4, 0.2, 0.45)\n",
    "    right_eye = get_landmark_centroid(0.2, 0.4, 0.55, 0.8)\n",
    "    nose = get_landmark_centroid(0.45, 0.7, 0.4, 0.6)\n",
    "    mouth = get_landmark_centroid(0.7, 0.95, 0.3, 0.7)\n",
    "    \n",
    "    dists = [\n",
    "        np.linalg.norm(left_eye - right_eye),\n",
    "        np.linalg.norm(left_eye - nose),\n",
    "        np.linalg.norm(right_eye - nose),\n",
    "        np.linalg.norm(left_eye - mouth),\n",
    "        np.linalg.norm(right_eye - mouth),\n",
    "        np.linalg.norm(nose - mouth)\n",
    "    ]\n",
    "    \n",
    "    eye_dist = dists[0] if dists[0] > 0 else 1.0\n",
    "    normalized_dists = [d / eye_dist for d in dists]\n",
    "    return np.array(normalized_dists, dtype=np.float32)\n",
    "\n",
    "print(\"Evaluasi Geometry-Based...\")\n",
    "mem_before = get_memory_usage()\n",
    "t0 = time.time()\n",
    "\n",
    "query_feats = {p: extract_geometry_features(face) for p, face in query_faces.items()}\n",
    "dataset_feats = np.array([extract_geometry_features(f[\"cropped_face\"]) for f in dataset_faces])\n",
    "\n",
    "feat_time = time.time() - t0\n",
    "mem_after = get_memory_usage()\n",
    "mem_used = max(0, mem_after - mem_before)\n",
    "\n",
    "evaluate_matching_model('Geometry-Based', query_feats, dataset_feats, dataset_faces, feat_time, mem_used)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Metode Holistik: PCA (Eigenfaces)\n",
    "Principal Component Analysis (PCA) mereduksi dimensi gambar dari wajah ter-resize dengan memproyeksikannya ke eigenfaces berdimensi 150."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Evaluasi PCA (Eigenfaces)... \")\n",
    "mem_before = get_memory_usage()\n",
    "t0 = time.time()\n",
    "\n",
    "# 1. Flatten wajah ke grayscale\n",
    "def flatten_gray_face(face_img):\n",
    "    gray = cv2.cvtColor(face_img, cv2.COLOR_BGR2GRAY)\n",
    "    return gray.flatten().astype(np.float32) / 255.0\n",
    "\n",
    "query_flat = np.array([flatten_gray_face(query_faces[p]) for p in [\"A\", \"B\", \"C\"]])\n",
    "dataset_flat = np.array([flatten_gray_face(f[\"cropped_face\"]) for f in dataset_faces])\n",
    "\n",
    "# 2. Fit PCA pada kumpulan wajah dataset\n",
    "n_components = min(150, len(dataset_faces))\n",
    "pca = PCA(n_components=n_components, svd_solver='randomized', whiten=True)\n",
    "pca.fit(dataset_flat)\n",
    "\n",
    "# 3. Proyeksi\n",
    "query_projected = pca.transform(query_flat)\n",
    "dataset_projected = pca.transform(dataset_flat)\n",
    "\n",
    "query_feats = {p: query_projected[i] for i, p in enumerate([\"A\", \"B\", \"C\"])}\n",
    "\n",
    "feat_time = time.time() - t0\n",
    "mem_after = get_memory_usage()\n",
    "mem_used = max(0, mem_after - mem_before)\n",
    "\n",
    "evaluate_matching_model('PCA (Holistik)', query_feats, dataset_projected, dataset_faces, feat_time, mem_used)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Metode Berbasis Fitur: LBP & HOG\n",
    "Mengekstrak fitur lokal menggunakan **Local Binary Pattern (LBP)** dan **Histogram of Oriented Gradients (HOG)**."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def extract_lbp_hist(face_img, radius=1, n_points=8):\n",
    "    gray = cv2.cvtColor(face_img, cv2.COLOR_BGR2GRAY)\n",
    "    lbp = local_binary_pattern(gray, n_points, radius, method=\"uniform\")\n",
    "    n_bins = n_points + 2\n",
    "    hist, _ = np.histogram(lbp.ravel(), bins=n_bins, range=(0, n_bins), density=True)\n",
    "    return hist.astype(np.float32)\n",
    "\n",
    "print(\"Evaluasi LBP...\")\n",
    "mem_before = get_memory_usage()\n",
    "t0 = time.time()\n",
    "\n",
    "query_feats = {p: extract_lbp_hist(query_faces[p]) for p in [\"A\", \"B\", \"C\"]}\n",
    "dataset_feats = np.array([extract_lbp_hist(f[\"cropped_face\"]) for f in dataset_faces])\n",
    "\n",
    "feat_time = time.time() - t0\n",
    "mem_after = get_memory_usage()\n",
    "mem_used = max(0, mem_after - mem_before)\n",
    "\n",
    "evaluate_matching_model('LBP (Berbasis Fitur)', query_feats, dataset_feats, dataset_faces, feat_time, mem_used)\n",
    "\n",
    "def extract_hog_vector(face_img):\n",
    "    gray = cv2.cvtColor(face_img, cv2.COLOR_BGR2GRAY)\n",
    "    feat = hog(gray, orientations=8, pixels_per_cell=(8, 8),\n",
    "               cells_per_block=(2, 2), visualize=False)\n",
    "    return feat.astype(np.float32)\n",
    "\n",
    "print(\"\\nEvaluasi HOG...\")\n",
    "mem_before = get_memory_usage()\n",
    "t0 = time.time()\n",
    "\n",
    "query_feats = {p: extract_hog_vector(query_faces[p]) for p in [\"A\", \"B\", \"C\"]}\n",
    "dataset_feats = np.array([extract_hog_vector(f[\"cropped_face\"]) for f in dataset_faces])\n",
    "\n",
    "feat_time = time.time() - t0\n",
    "mem_after = get_memory_usage()\n",
    "mem_used = max(0, mem_after - mem_before)\n",
    "\n",
    "evaluate_matching_model('HOG (Berbasis Fitur)', query_feats, dataset_feats, dataset_faces, feat_time, mem_used)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Metode Hibrida: LBP + PCA\n",
    "Menggabungkan tekstur lokal dari LBP mentah dengan reduksi dimensi PCA (50 komponen)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def extract_raw_lbp(face_img, radius=1, n_points=8):\n",
    "    gray = cv2.cvtColor(face_img, cv2.COLOR_BGR2GRAY)\n",
    "    lbp = local_binary_pattern(gray, n_points, radius, method=\"uniform\")\n",
    "    return lbp.ravel().astype(np.float32)\n",
    "\n",
    "print(\"Evaluasi LBP + PCA (Hibrida)...\")\n",
    "mem_before = get_memory_usage()\n",
    "t0 = time.time()\n",
    "\n",
    "query_raw_lbp = np.array([extract_raw_lbp(query_faces[p]) for p in [\"A\", \"B\", \"C\"]])\n",
    "dataset_raw_lbp = np.array([extract_raw_lbp(f[\"cropped_face\"]) for f in dataset_faces])\n",
    "\n",
    "n_components_hyb = min(50, len(dataset_faces))\n",
    "pca_lbp = PCA(n_components=n_components_hyb, svd_solver='randomized', whiten=True)\n",
    "pca_lbp.fit(dataset_raw_lbp)\n",
    "\n",
    "query_projected = pca_lbp.transform(query_raw_lbp)\n",
    "dataset_projected = pca_lbp.transform(dataset_raw_lbp)\n",
    "\n",
    "query_feats = {p: query_projected[i] for i, p in enumerate([\"A\", \"B\", \"C\"])}\n",
    "\n",
    "feat_time = time.time() - t0\n",
    "mem_after = get_memory_usage()\n",
    "mem_used = max(0, mem_after - mem_before)\n",
    "\n",
    "evaluate_matching_model('LBP + PCA (Hibrida)', query_feats, dataset_projected, dataset_faces, feat_time, mem_used)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Metode Deep Learning: Facenet (DeepFace)\n",
    "Mengekstrak embedding berdimensi 128 dari model Deep Learning Facenet (diload dari cache jika tersedia)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Evaluasi Facenet...\")\n",
    "mem_before = get_memory_usage()\n",
    "t0 = time.time()\n",
    "\n",
    "# 1. Ekstraksi Fitur Kueri\n",
    "query_feats = {}\n",
    "for p in [\"A\", \"B\", \"C\"]:\n",
    "    q_img = cv2.cvtColor(query_faces[p], cv2.COLOR_GRAY2BGR) if len(query_faces[p].shape) == 2 else query_faces[p]\n",
    "    rep = DeepFace.represent(img_path=q_img, model_name=\"Facenet\", enforce_detection=False, detector_backend=\"skip\")\n",
    "    query_feats[p] = np.array(rep[0][\"embedding\"], dtype=np.float32)\n",
    "\n",
    "# 2. Ekstraksi Fitur Dataset\n",
    "dataset_feats_list = []\n",
    "for idx, face_meta in enumerate(dataset_faces):\n",
    "    img_name = face_meta[\"img_name\"]\n",
    "    bbox = face_meta[\"bbox\"]\n",
    "    \n",
    "    # Cek cache Facenet\n",
    "    cached_found = False\n",
    "    if img_name in preloaded_caches[\"Facenet\"]:\n",
    "        for cached_entry in preloaded_caches[\"Facenet\"][img_name]:\n",
    "            if list(cached_entry[\"bbox\"]) == list(bbox):\n",
    "                dataset_feats_list.append(cached_entry[\"embedding\"])\n",
    "                cached_found = True\n",
    "                break\n",
    "                \n",
    "    if not cached_found:\n",
    "        import gc\n",
    "        # Ekstraksi Baru dan simpan cache\n",
    "        f_img = face_meta[\"cropped_face\"]\n",
    "        emb = extract_deepface_embedding(f_img, \"Facenet\")\n",
    "        norm = np.linalg.norm(emb)\n",
    "        if norm > 0:\n",
    "            emb = emb / norm\n",
    "        handlers[\"Facenet\"].simpan_cache(img_name, emb, bbox)\n",
    "        dataset_feats_list.append(emb)\n",
    "        del f_img, emb\n",
    "        if idx % 100 == 0:\n",
    "            gc.collect()\n",
    "dataset_feats = np.array(dataset_feats_list)\n",
    "feat_time = time.time() - t0\n",
    "mem_after = get_memory_usage()\n",
    "mem_used = max(0, mem_after - mem_before)\n",
    "\n",
    "evaluate_matching_model('DeepFace (Facenet)', query_feats, dataset_feats, dataset_faces, feat_time, mem_used)\n",
    "\n",
    "# Bersihkan session Keras untuk mengosongkan RAM sebelum memuat model berikutnya\n",
    "import tensorflow as tf\n",
    "tf.keras.backend.clear_session()\n",
    "import gc\n",
    "gc.collect()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Metode Deep Learning: VGG-Face (DeepFace)\n",
    "Mengekstrak embedding berdimensi 2622 dari model Deep Learning VGG-Face (diload dari cache jika tersedia)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Evaluasi VGG-Face...\")\n",
    "mem_before = get_memory_usage()\n",
    "t0 = time.time()\n",
    "\n",
    "# 1. Ekstraksi Fitur Kueri\n",
    "query_feats = {}\n",
    "for p in [\"A\", \"B\", \"C\"]:\n",
    "    q_img = cv2.cvtColor(query_faces[p], cv2.COLOR_GRAY2BGR) if len(query_faces[p].shape) == 2 else query_faces[p]\n",
    "    rep = DeepFace.represent(img_path=q_img, model_name=\"VGG-Face\", enforce_detection=False, detector_backend=\"skip\")\n",
    "    query_feats[p] = np.array(rep[0][\"embedding\"], dtype=np.float32)\n",
    "\n",
    "# 2. Ekstraksi Fitur Dataset\n",
    "dataset_feats_list = []\n",
    "for idx, face_meta in enumerate(dataset_faces):\n",
    "    img_name = face_meta[\"img_name\"]\n",
    "    bbox = face_meta[\"bbox\"]\n",
    "    \n",
    "    cached_found = False\n",
    "    if img_name in preloaded_caches[\"VGG-Face\"]:\n",
    "        for cached_entry in preloaded_caches[\"VGG-Face\"][img_name]:\n",
    "            if list(cached_entry[\"bbox\"]) == list(bbox):\n",
    "                dataset_feats_list.append(cached_entry[\"embedding\"])\n",
    "                cached_found = True\n",
    "                break\n",
    "                \n",
    "    if not cached_found:\n",
    "        import gc\n",
    "        f_img = face_meta[\"cropped_face\"]\n",
    "        emb = extract_deepface_embedding(f_img, \"VGG-Face\")\n",
    "        norm = np.linalg.norm(emb)\n",
    "        if norm > 0:\n",
    "            emb = emb / norm\n",
    "        handlers[\"VGG-Face\"].simpan_cache(img_name, emb, bbox)\n",
    "        dataset_feats_list.append(emb)\n",
    "        del f_img, emb\n",
    "        if idx % 50 == 0:\n",
    "            gc.collect()\n",
    "dataset_feats = np.array(dataset_feats_list)\n",
    "feat_time = time.time() - t0\n",
    "mem_after = get_memory_usage()\n",
    "mem_used = max(0, mem_after - mem_before)\n",
    "\n",
    "evaluate_matching_model('DeepFace (VGG-Face)', query_feats, dataset_feats, dataset_faces, feat_time, mem_used)\n",
    "\n",
    "# Bersihkan session Keras untuk mengosongkan RAM sebelum memuat model berikutnya\n",
    "import tensorflow as tf\n",
    "tf.keras.backend.clear_session()\n",
    "import gc\n",
    "gc.collect()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Metode Deep Learning: ArcFace (DeepFace)\n",
    "Mengekstrak embedding berdimensi 512 dari model Deep Learning ArcFace (diload dari cache jika tersedia). Ini adalah model yang digunakan oleh sistem utama GUI."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Evaluasi ArcFace...\")\n",
    "mem_before = get_memory_usage()\n",
    "t0 = time.time()\n",
    "\n",
    "# 1. Ekstraksi Fitur Kueri\n",
    "query_feats = {}\n",
    "for p in [\"A\", \"B\", \"C\"]:\n",
    "    q_img = cv2.cvtColor(query_faces[p], cv2.COLOR_GRAY2BGR) if len(query_faces[p].shape) == 2 else query_faces[p]\n",
    "    rep = DeepFace.represent(img_path=q_img, model_name=\"ArcFace\", enforce_detection=False, detector_backend=\"skip\")\n",
    "    query_feats[p] = np.array(rep[0][\"embedding\"], dtype=np.float32)\n",
    "\n",
    "# 2. Ekstraksi Fitur Dataset\n",
    "dataset_feats_list = []\n",
    "for idx, face_meta in enumerate(dataset_faces):\n",
    "    img_name = face_meta[\"img_name\"]\n",
    "    bbox = face_meta[\"bbox\"]\n",
    "    \n",
    "    cached_found = False\n",
    "    if img_name in preloaded_caches[\"ArcFace\"]:\n",
    "        for cached_entry in preloaded_caches[\"ArcFace\"][img_name]:\n",
    "            if list(cached_entry[\"bbox\"]) == list(bbox):\n",
    "                dataset_feats_list.append(cached_entry[\"embedding\"])\n",
    "                cached_found = True\n",
    "                break\n",
    "                \n",
    "    if not cached_found:\n",
    "        import gc\n",
    "        f_img = face_meta[\"cropped_face\"]\n",
    "        emb = extract_deepface_embedding(f_img, \"ArcFace\")\n",
    "        norm = np.linalg.norm(emb)\n",
    "        if norm > 0:\n",
    "            emb = emb / norm\n",
    "        handlers[\"ArcFace\"].simpan_cache(img_name, emb, bbox)\n",
    "        dataset_feats_list.append(emb)\n",
    "        del f_img, emb\n",
    "        if idx % 50 == 0:\n",
    "            gc.collect()\n",
    "dataset_feats = np.array(dataset_feats_list)\n",
    "feat_time = time.time() - t0\n",
    "mem_after = get_memory_usage()\n",
    "mem_used = max(0, mem_after - mem_before)\n",
    "\n",
    "evaluate_matching_model('DeepFace (ArcFace)', query_feats, dataset_feats, dataset_faces, feat_time, mem_used)\n",
    "\n",
    "# Bersihkan session Keras setelah selesai pengujian\n",
    "import tensorflow as tf\n",
    "tf.keras.backend.clear_session()\n",
    "import gc\n",
    "gc.collect()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9. Visualisasi dan Perbandingan Kinerja\n",
    "Menampilkan tabel perbandingan DataFrame lengkap untuk kedelapan model, dan memvisualisasikan F1-Score, waktu eksekusi total (ekstraksi + pencocokan), serta tambahan penggunaan RAM."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_results = pd.DataFrame(results)\n",
    "print(\"\\n--- Hasil Perbandingan Lengkap (8 Model) ---\")\n",
    "print(df_results.to_string(index=False))\n",
    "\n",
    "# Tableau 10 color palette untuk visualisasi premium\n",
    "colors = ['#4E79A7', '#F28E2B', '#E15759', '#76B7B2', '#59A14F', '#EDC948', '#B07AA1', '#FF9DA7']\n",
    "\n",
    "plt.figure(figsize=(18, 6))\n",
    "\n",
    "# 1. Plot F1-Score\n",
    "plt.subplot(1, 3, 1)\n",
    "bars1 = plt.bar(df_results['Model'], df_results['F1-Score'], color=colors[:len(df_results)])\n",
    "plt.title('F1-Score Model (Tertinggi Terbaik)', fontsize=12, fontweight='bold')\n",
    "plt.ylim(0, 1.15)\n",
    "plt.xticks(rotation=45, ha='right', fontsize=9)\n",
    "plt.ylabel('F1-Score')\n",
    "for bar in bars1:\n",
    "    yval = bar.get_height()\n",
    "    plt.text(bar.get_x() + bar.get_width()/2.0, yval + 0.02, f\"{yval:.2f}\", ha='center', va='bottom', fontsize=9)\n",
    "\n",
    "# 2. Plot Stacked Waktu Komputasi per Tahap (Deteksi + Ekstraksi + Inferensi)\n",
    "plt.subplot(1, 3, 2)\n",
    "det_times = df_results['Detection Time (s)']\n",
    "feat_times = df_results['Feature Extraction Time (s)']\n",
    "infer_times = df_results['Inference Time (s)']\n",
    "plt.bar(df_results['Model'], det_times, color='#B07AA1', label='Deteksi & Alignment')\n",
    "plt.bar(df_results['Model'], feat_times, bottom=det_times, color='#4E79A7', label='Ekstraksi Fitur')\n",
    "plt.bar(df_results['Model'], infer_times, bottom=det_times + feat_times, color='#F28E2B', label='Inferensi/Matching')\n",
    "total_time = det_times + feat_times + infer_times\n",
    "plt.title('Waktu Komputasi per Tahap (detik)', fontsize=12, fontweight='bold')\n",
    "plt.xticks(rotation=45, ha='right', fontsize=9)\n",
    "plt.ylabel('Waktu (detik)')\n",
    "plt.legend(fontsize=7, loc='upper left')\n",
    "for i, total in enumerate(total_time):\n",
    "    plt.text(i, total + (total * 0.02) + 0.05, f\"{total:.2f}s\", ha='center', va='bottom', fontsize=9)\n",
    "\n",
    "# 3. Plot Memory Usage\n",
    "plt.subplot(1, 3, 3)\n",
    "bars3 = plt.bar(df_results['Model'], df_results['Memory Usage (MB)'], color=colors[:len(df_results)])\n",
    "plt.title('Penggunaan Memori Tambahan (MB)', fontsize=12, fontweight='bold')\n",
    "plt.xticks(rotation=45, ha='right', fontsize=9)\n",
    "plt.ylabel('Memori (MB)')\n",
    "for bar in bars3:\n",
    "    yval = bar.get_height()\n",
    "    # Jaga formatting\n",
    "    plt.text(bar.get_x() + bar.get_width()/2.0, yval + 0.1, f\"{yval:.1f} MB\", ha='center', va='bottom', fontsize=9)\n",
    "\n",
    "plt.tight_layout()\n",
    "assets_dir = os.path.join(project_root, \"assets\")\n",
    "os.makedirs(assets_dir, exist_ok=True)\n",
    "plt.savefig(os.path.join(assets_dir, \"perbandingan_kinerja.png\"), dpi=300, bbox_inches=\"tight\")\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.0"
  }
 }
}

import copy

def build_detector_notebook(detector_type):
    nb = copy.deepcopy(notebook_content)
    
    # 1. Modify title in cell 0
    nb["cells"][0]["source"][0] = f"# Eksplorasi Algoritma Face Recognition ({detector_type.upper()} Detector)\n"
    
    # 2. Modify detector in cell 3
    cell3_source = nb["cells"][3]["source"]
    for i, line in enumerate(cell3_source):
        if "detector = FaceDetector()" in line:
            cell3_source[i] = line.replace("detector = FaceDetector()", f"detector = FaceDetector(\"{detector_type}\")")
        if '".face_cache_{self.model_name}"' in line:
            cell3_source[i] = line.replace('".face_cache_{self.model_name}"', f'".face_cache_{detector_type}_{{self.model_name}}"')
            
    # 3. Modify savefig in cell 19
    cell19_source = nb["cells"][19]["source"]
    for i, line in enumerate(cell19_source):
        if "perbandingan_kinerja.png" in line:
            cell19_source[i] = line.replace("perbandingan_kinerja.png", f"perbandingan_kinerja_{detector_type}.png")
            
    current_dir = os.path.dirname(os.path.abspath(__file__))
    notebook_path = os.path.join(current_dir, f"notebook_{detector_type}.ipynb")
    with open(notebook_path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1)
    print(f"Jupyter Notebook ({detector_type}) berhasil dibentuk di: {notebook_path}")

build_detector_notebook("mtcnn")
build_detector_notebook("scrfd")
